import '../styles/globals.scss'

import Layout from "../layout/Layout";
import Head from "next/head";

function MyApp({Component, pageProps}) {
    return (
        <Layout>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>

                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <Component {...pageProps} />
        </Layout>
    )
}

export default MyApp
